<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Jyothi" failures="0" tests="1" name="runners.RetryScenarioRunner" time="41.732" errors="1" timestamp="2025-06-16T15:36:09 GST" skipped="0">
  <testcase classname="runners.RetryScenarioRunner" name="runScenario" time="41.732">
    <error message="Cannot invoke &quot;Learn.com.magneto.base.TestContext.getExtentTest()&quot; because &quot;this.testContext&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "Learn.com.magneto.base.TestContext.getExtentTest()" because "this.testContext" is null
at Learn.com.magento.utils.RetryAnalyzer.retry(RetryAnalyzer.java:19)
at org.testng.internal.invokers.TestInvoker.shouldRetryTestMethod(TestInvoker.java:577)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:749)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- runScenario -->
</testsuite> <!-- runners.RetryScenarioRunner -->
